UseSwagger: true
SessionExpireSpan: 00:20:00
Logging:
    LogFolder: ../logs
    LogLevel:
        Default: Debug
        Microsoft.AspNetCore: Warning
        Microsoft.AspNetCore.HttpLogging.HttpLoggingMiddleware: Information
        Sentry.ISentryClient: Warning
        DbLoggerCategory.Database.Command: Warning
        Microsoft.AspNetCore.Mvc.ModelBinding.ModelBinderFactory: Warning
Db:
    Version: 8.0.21
    UserDb:
        ConnectionStrList:
            - Server=localhost;Port=3306;Database=TestUserDb;Uid=root;Pwd=tjrudwlq!; #테스트중이라 그냥 올림. 중요 X
    AuthDb:
        ConnectionStrList:
            - Server=localhost;Port=3306;Database=TestAuthDb;Uid=root;Pwd=tjrudwlq!;