UseSwagger: true
asb: true
Db:
    Version: 8.0.21
    UserDb:
        ConnectionStrList:
            - Server=localhost;Port=3306;Database=TestDb;Uid=root;Pwd=tjrudwlq!; #테스트중이라 그냥 올림. 중요 XtjrudElq,서경찝ㅣ!