UseSwagger: true
asb: true
Db:
    Version: 8.0.21
    UserDb:
        ConnectionStrList:
            - Server=localhost;Port=3306;Database=TestUserDb;Uid=root;Pwd=tjrudwlq!; #테스트중이라 그냥 올림. 중요 X
    AuthDb:
        ConnectionStrList:
            - Server=localhost;Port=3306;Database=TestAuthDb;Uid=root;Pwd=tjrudwlq!;