UseUserLock: true
UserLockTimeoutSpan: 00:10:00
Proto:
    CsvPath: ../../Data/Csv/Proto
Logging:
    LogFolder: ../logs
    LogLevel:
        Default: Debug
        Microsoft.AspNetCore: Warning
        Microsoft.AspNetCore.HttpLogging.HttpLoggingMiddleware: Information
        Sentry.ISentryClient: Warning
        DbLoggerCategory.Database.Command: Warning
        Microsoft.AspNetCore.Mvc.ModelBinding.ModelBinderFactory: Warning
Cache:
    Type: Redis
    ConnectionString: "localhost:6379"
    DefaultTtl: 00:30:00
Db:
    Version: 8.0.21
    Type: MySql
    UserDb:
        ConnectionStrList:
            - Server=localhost;Port=3306;Database=UserDb;Uid=root;Pwd=tjrudwlq!;Pooling=True; # 비번 노출 개선 필요. 로컬이라 일단 냅두는데 솔루션 필요함.
    AuthDb:
        ConnectionStrList:
            - Server=localhost;Port=3306;Database=AuthDb;Uid=root;Pwd=tjrudwlq!;Pooling=True;
    CenterDb:
        ConnectionStrList:
            - Server=localhost;Port=3306;Database=CenterDb;Uid=root;Pwd=tjrudwlq!;Pooling=True;
Game:
    UseSwagger: true
    SessionExpireSpan: 00:20:00
    SessionGracePeriodSpan: 30.00:00:00
    IsShowErrorDetail: true
    UseStrictValidation: true
    DefaultPlayerPath: Data/DefaultPlayer.json
    ForceContentType: application/protobuf
